
deploy_for_serverless.yml

name: 'deploy_for_serverless'

on:
  wat      enc_server_disabled:

        description: '指定部署区域，腾讯云函数默认部署在  ap-guangzhou(广州)，阿里云函数默认部署在  cn-shanghai(上海)，不清楚请不要填写'
        required: false
        default: ''

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v2
      with: 
        repository: ${{ secrets.REPOSITORY }}
        ref: ${{ secrets.REF }}
    
    - name: 执行部署脚本
      run: bash ./serverless/deploy.sh
      env:
          SERVERLESS_PLATFORM_VENDOR: tencent #serverless 境外默认为 aws，配置为腾讯
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
          ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
          REGION: ${{ github.event.inputs.REGION }}
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          ACCESS_KEY_SECRET: ${{ secrets.ACCESS_KEY_SECRET }}
          TIMEOUT: 120
          CRON: ${{ github.event.inputs.CRON }}
          enc_server_disabled: ${{ github.event.inputs.enc_server_disabled }}
